### ISSUE TITLE
Server Create Object Fail

### ISSUE THREAD

**Issue by sl-fedegiust** [dikoga/redis-com-client#1]
Hi,

I've installed Redis and StackExchange.Redis on a VM which is running Classic ASP.

I've downloaded your wrapper and build it using Visual Studio. Also registered successfully following your instructions.

But I'm getting an error when trying to actually use it

> Server object error 'ASP 0177 : 800401f3'
> Server.CreateObject Failed

Here's the code I'm using to test

```
    Dim Cache
    Set Cache = Server.CreateObject("redis-com-client")

    Cache.Init "prefix1"

    Cache.Add "Key1", "Value1"

    Response.Write "Tesing Redis"

    Response.Write Cache("Key1")
```

**Comment by dikoga** [comment]
Hi,

Try this instead:  Set Cache = Server.CreateObject("CacheManager")

The object name is the name defined on the ProgId attribute.

**Comment by fedegiust** [comment]
yes! That worked! thanks
