### ISSUE TITLE
Error removing all

### ISSUE THREAD

**Issue by fernandozap2** [dikoga/redis-com-client#2]
on execute command Cache.RemoveAll(), the error occurs:

> StackExchange.Redis.StrongName error '80131500'
> ERR unknown command 'EVAL'

Compiled using:
VS2019 Comunity
.Net Framework 4.6.2
StackExchange.Redis 1.2.6.0
Newtonsoft.Json 12.0.0.0

In VisualStudio is the same error running the tests.

Test Details:
> Test Name:	RemoveAllFromThisKey
> Test FullName:	Test Detail Summary
> Test Source:	 d:\Downloads\redis-com-client-master\redis-com-client-test\BasicTest.cs : line 96
> Test Outcome:	Failed
> Test Duration:	0:00:00
> 
> Test Name:	RemoveAllFromThisKey
> Test Outcome:	Failed
> Result StackTrace:	
> at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2128
>    at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
>    at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1059
>    at redis_com_client.CacheManager.RemoveAll() in d:\Downloads\redis-com-client-master\redis-com-client\CacheManager.cs:line 30
>    at redis_com_client_test.BasicTest.RemoveAllFromThisKey() in d:\Downloads\redis-com-client-master\redis-com-client-test\BasicTest.cs:line 104
> Result Message:	
> Test method redis_com_client_test.BasicTest.RemoveAllFromThisKey threw exception: 
> StackExchange.Redis.RedisServerException: ERR unknown command 'EVAL'

Thanks!

**Comment by Neopallium** [comment]
> > ERR unknown command 'EVAL'

Your redis version is older then 2.6.  The `EVAL` command was added to redis in version 2.6
The latest version of redis for windows that I have found is 3.2 and the `RemoveAll` works with it.
